#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
while (( hour <= 12 ))
do
	echo "Hour: $hour"
	minute=1
	while (( minute <= 59 ))
	do
		echo "Minutes: $minute"
		(( minute++ ))
	done
	(( hour++ ))
done
